image: mailgun/gobase2
env:
  - GOROOT=/opt/go
  - PATH=$PATH:/opt/go/bin
  - GOPATH=/var/cache/drone
script:
  - echo "gopath is: $GOPATH"
  - echo $PATH
  - go get -v -u code.google.com/p/go.tools/cover
  - go get -v -u github.com/axw/gocov
  - go install github.com/axw/gocov/gocov
  - go get -v -u github.com/golang/glog
  - go get -v -u github.com/mailgun/glogutils
  - go get -v -u github.com/axw/gocov
  - go get -v -u launchpad.net/gocheck
  - go get -v -u github.com/mailgun/gocql
  - go get -v -u github.com/robertkrimen/otto
  - go get -v -u github.com/coreos/go-etcd/etcd
  - go get -v -u github.com/mailgun/minheap
  - go test -v ./...
