language: go
go:
 - 1.2
 - 1.1.2
 - 1.1.1
 - 1.1
 - tip

install:
 - export PATH=$HOME/gopath/bin:$PATH
 - go get -v github.com/golang/glog
 - go get -v launchpad.net/gocheck
 - go get -v github.com/mailgun/gocql
 - go get -v github.com/mailgun/glogutils
 - go get -v -u github.com/robertkrimen/otto
 - go get -v -u github.com/coreos/go-etcd/etcd
 - go get -v -u github.com/mailgun/minheap

script:
 - go test -v ./...
